language: nodejs
node_js:
- 14.16.0

cache:
  directories:
    - ./node_modules
install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

before_deploy:
  - npm run build --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist/personal_portfolio
  on:
    branch: main
  fdqn: ajaykarthick.me
